### ISSUE TITLE
(bug): version splitting does not account for org scoped packages

### ISSUE THREAD

**Issue by moltar** [CloudSnorkel/cdk-turbo-layers#15]
https://github.com/CloudSnorkel/cdk-turbo-layers/blob/4c77998ec34a699a5a1bb7bfba7940663ca25bff/src/nodejs.ts#LL39C42-L39C56

From the browser console:

```
> "@aws-sdk/client-s3@3.259.0".split('@', 2)
< Array [ "", "aws-sdk/client-s3" ]
```

Then we end up with a `package.json` similar to this:

```json
{"dependencies":{"":"aws-sdk/client-s3"}}
```

**Comment by moltar** [comment]
Maybe this little helper could be used?

https://github.com/egoist/parse-package-name

**Comment by kichik** [comment]
Thanks! We can't use that external library because it's not JSII enabled, but I'm sure we can create a little workaround.

**Comment by moltar** [comment]
Right, forgot about the JSII part.

Well, the library is tiny, so can probably just copy paste the code.

**Comment by moltar** [comment]
Thanks, works! 🎉
