### ISSUE TITLE
Cannot import (easily) in Python

### ISSUE THREAD

**Issue by stephen-christie-ss** [CloudSnorkel/cdk-turbo-layers#22]
In Python, the module is named `cloudsnorkel.cdk_turbo-layers`. Because `-` is a reserved keyword (the subtraction operator), you cannot import this the normal way, e.g. `import cloudsnorkel.cdk_turbo-layers as turbo_layers`. Instead, you have to `import importlib` to then use `turbo_layers = importlib.import_module('cloudsnorkel.cdk_turbo-layers')`.

**Comment by kichik** [comment]
Well that's quite an embarrassing typo. Thank you for reporting! 0.0.3 will be out with a fix in a few minutes.
